[build]
  command = "cd frontend && npm run build"
  publish = "frontend/.next"

[functions]
  directory = "netlify/edge-functions"
  node_bundler = "esbuild"

[dev]
  command = "cd frontend && npm run dev"
  port = 3000
  targetPort = 3000

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/builders/api"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200